# Generated by Django 4.2.4 on 2023-08-21 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=50)),
                ('waktu', models.TimeField()),
                ('tanggal', models.DateField()),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presensi.status')),
            ],
        ),
    ]
