# Generated by Django 4.2.2 on 2023-08-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
        ('presensi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presensi',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='presensi',
            name='tanggal',
        ),
        migrations.RemoveField(
            model_name='presensi',
            name='waktu',
        ),
        migrations.AddField(
            model_name='presensi',
            name='tgl',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='nama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.biodata'),
        ),
    ]
