# Generated by Django 4.2.2 on 2023-08-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0002_remove_presensi_nip_remove_presensi_tanggal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='ket',
        ),
    ]
