# Generated by Django 4.2.2 on 2023-09-05 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0003_remove_status_ket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
