# Generated by Django 4.2.2 on 2023-09-11 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0006_alter_presensi_tgl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='tgl',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
