# Generated by Django 4.2.2 on 2023-09-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
