# Generated by Django 4.2.2 on 2023-09-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perizinan', '0008_alter_perizinan_tgl'),
        ('absen', '0003_alter_absen_tgl'),
        ('presensi', '0009_alter_presensi_tgl'),
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='absen.absen')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.biodata')),
                ('perizinan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perizinan.perizinan')),
                ('presensi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presensi.presensi')),
            ],
        ),
    ]
