# Generated by Django 4.2.2 on 2023-09-13 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0008_alter_perizinan_tgl'),
        ('absen', '0003_alter_absen_tgl'),
        ('presensi', '0009_alter_presensi_tgl'),
        ('biodata', '0001_initial'),
        ('rekapitulasi', '0002_rename_absen_rekap_absen_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekap',
            name='absen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absen.absen'),
        ),
        migrations.AlterField(
            model_name='rekap',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biodata.biodata'),
        ),
        migrations.AlterField(
            model_name='rekap',
            name='perizinan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perizinan.perizinan'),
        ),
        migrations.AlterField(
            model_name='rekap',
            name='presensi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presensi.presensi'),
        ),
    ]
