# Generated by Django 4.2.4 on 2023-08-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perizinan',
            name='tglawal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
