# Generated by Django 4.2.2 on 2023-08-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0002_alter_perizinan_tglawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perizinan',
            old_name='tglawal',
            new_name='tgl',
        ),
        migrations.RemoveField(
            model_name='perizinan',
            name='tglakhir',
        ),
    ]
