# Generated by Django 4.2.2 on 2023-08-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0003_rename_tglawal_perizinan_tgl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perizinan',
            name='tgl',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
