# Generated by Django 4.2.2 on 2023-08-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
        ('perizinan', '0005_alter_perizinan_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perizinan',
            name='nama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.biodata'),
        ),
    ]
